### ISSUE TITLE
Support TypeScript definition for Function Props

### ISSUE THREAD

**Issue by garrypolley** [Crownpeak/DXM-React-SDK#10]
If I have the following component: 

```jsx
import React from 'react';
import {CmsDataCache, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';


const MainNavigation = (props) => {
    CmsDataCache.setComponent("MainNavigation");

    const heading = new CmsField('heading', CmsFieldTypes.TEXT, props?.heading);

    return (
        <div>{heading}</div>
    )
}

export default MainNavigation;
```

The command `npx crownpeak scaffold --dry-run --verbose` has no issues. 

However, if I put a type definition for the prop, the following error occurs: 

```sh
➜  siteFolder git:(main) ✗ npx crownpeak scaffold --dry-run --verbose

/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:806
      throw err;
      ^

SyntaxError: Unexpected token, expected "," (5:29)
    at Object._raise (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:799:17)
    at Object.raiseWithData (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:792:17)
    at Object.raise (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:786:17)
    at Object.unexpected (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9089:16)
    at Object.expect (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9075:28)
    at Object.parseParenAndDistinguishExpression (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:10591:14)
    at Object.parseExprAtom (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:10311:21)
    at Object.parseExprAtom (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:4748:20)
    at Object.parseExprSubscripts (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9976:23)
    at Object.parseUpdate (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9956:21)
    at Object.parseMaybeUnary (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9945:17)
    at Object.parseExprOps (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9815:23)
    at Object.parseMaybeConditional (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9789:23)
    at Object.parseMaybeAssign (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9752:21)
    at /Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9718:39
    at Object.allowInAnd (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:11442:16)
    at Object.parseMaybeAssignAllowIn (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:9718:17)
    at Object.parseVar (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:12243:70)
    at Object.parseVarStatement (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:12052:10)
    at Object.parseStatementContent (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:11644:21)
    at Object.parseStatement (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:11577:17)
    at Object.parseBlockOrModuleBlockBody (/Users/userFolder/src/siteFolder/node_modules/@babel/parser/lib/index.js:12159:25) {
  loc: Position { line: 5, column: 29 },
  pos: 137
}
```

I think this is something to do with how the babel parser is rendering the type script.

The component with a type for the props. 

```jsx
import React from 'react';
import {CmsDataCache, CmsField, CmsFieldTypes} from 'crownpeak-dxm-react-sdk';


const MainNavigation = (props: any) => {
    CmsDataCache.setComponent("MainNavigation");

    const heading = new CmsField('heading', CmsFieldTypes.TEXT, props?.heading);

    return (
        <div>{heading}</div>
    )
}

export default MainNavigation;
```

**Comment by richard-lund** [comment]
I've checked in a fix for this - it will go out with the next release.
